FROM golang:latest
MAINTAINER Mayflower GmbH

RUN go get -d github.com/mayflower/docker-ls/...
RUN go generate github.com/mayflower/docker-ls/...
RUN go install github.com/mayflower/docker-ls/cli/...

ENTRYPOINT ["/go/bin/docker-ls"]
